# Generated by Django 5.2.14 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='seasonEnd',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='December', max_length=20, verbose_name='Season End'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='seasonStart',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=20, verbose_name='Season Start'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='stock_alert_threshold',
            field=models.IntegerField(default=0, verbose_name='Alert Threshold'),
        ),
    ]
