# Generated by Django 5.2.12 on 2026-03-21 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='producer',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recurrence_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_expiry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seasonEnd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seasonStart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_alert_threshold',
        ),
        migrations.RemoveField(
            model_name='review',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
        migrations.AddField(
            model_name='order',
            name='num_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], default='Spring', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Producer', 'Producer'), ('Organisation', 'Organisation'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
