# Generated by Django 5.2.11 on 2026-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
