# Generated by Django 5.2.14 on 2026-05-06 23:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_stock_user_charity_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='max_order_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='surplus_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quality_class',
            field=models.CharField(choices=[('A', 'A - Premium'), ('B', 'B - Standard'), ('C', 'C - Economy'), ('D', 'D - Basic'), ('Discounted', 'Surplus / Discount')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='seasonEnd',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='December', max_length=20, verbose_name='Season End'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='seasonStart',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='January', max_length=20, verbose_name='Season Start'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='stock_alert_threshold',
            field=models.IntegerField(default=0, verbose_name='Alert Threshold'),
        ),
        migrations.CreateModel(
            name='ProducerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to='core.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('order', 'producer')},
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='producer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.producerorder'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='producer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.producerorder'),
        ),
    ]
